# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f31d4986226eeb79dfa074b1786d5f652af75b3856229528a92ccbb31affe3a1d282c8310155cded929fab6f8b938b678542a1ad806a9a01fe69751c10c828d8

test:
  secret_key_base: 31c735ea412b5ea762deabdee5cc8dddcdc4ef4e9827035c2d669256f74c5344587f69b39477827a51ae7527b27582f63e5cc01424cb3733b3dcdc2b19988ff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
